import React from "react";

const Page = () => {
  return (
    <div className="">
      <h2 className="text-center text-xl font-bold my-3 mt-5">
        dynamic form generated by admin ver 2
      </h2>
      <div></div>
    </div>
  );
};

export default Page;
